In [ ]:
import pathlib as Path
import pandas as pd

relative_path=Path.Path('../Content')/"BikeIndia.csv"
dfBike=pd.read_csv(relative_path)

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,1/1/2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,2/1/2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,5/29/2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,5/30/2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,5/31/2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,542,26-06-2019,3,1,6,0,2,1,1,25.864153,29.73520,37.3333,23.292014,1077,6365,7442
542,543,27-06-2019,3,1,6,0,3,1,1,28.597500,32.03960,36.0000,18.208925,1077,6258,7335
543,544,28-06-2019,3,1,6,0,4,1,1,30.715847,33.77560,42.2500,11.500550,921,5958,6879
544,545,29-06-2019,3,1,6,0,5,1,1,34.200847,39.33065,48.8750,11.082939,829,4634,5463
545,546,30-06-2019,3,1,6,0,6,0,1,31.365000,34.37540,60.1250,10.791757,1455,4232,5687

In [ ]:
dfBike_firstHalf=dfBike[dfBike.mnth<=6]
dfBike_secondHalf=dfBike[dfBike.mnth>6]

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,1/1/2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,2/1/2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,5/29/2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,5/30/2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,5/31/2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,542,26-06-2019,3,1,6,0,2,1,1,25.864153,29.73520,37.3333,23.292014,1077,6365,7442
542,543,27-06-2019,3,1,6,0,3,1,1,28.597500,32.03960,36.0000,18.208925,1077,6258,7335
543,544,28-06-2019,3,1,6,0,4,1,1,30.715847,33.77560,42.2500,11.500550,921,5958,6879
544,545,29-06-2019,3,1,6,0,5,1,1,34.200847,39.33065,48.8750,11.082939,829,4634,5463
545,546,30-06-2019,3,1,6,0,6,0,1,31.365000,34.37540,60.1250,10.791757,1455,4232,5687

In [4]:
dfBike_firstHalf.describe()

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,362.000000,362.000000,362.000000,362.000000,362.000000,362.000000,362.000000,362.000000,362.000000,362.000000,362.000000,362.000000,362.000000,362.000000,362.000000
mean,273.500000,1.618785,0.500000,3.508287,0.024862,2.994475,0.687845,1.381215,18.314966,21.557366,59.915757,13.927939,777.284530,3257.226519,4034.511050
std,190.094906,0.589362,0.500692,1.712327,0.155920,2.005525,0.464014,0.519408,7.305315,8.029563,15.376103,5.191067,717.020721,1508.092982,1956.007015
min,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,2.424346,3.953480,0.000000,3.042356,9.000000,416.000000,431.000000
25%,91.250000,1.000000,0.000000,2.000000,0.000000,1.000000,0.000000,1.000000,12.009587,14.653525,48.885425,10.041491,214.750000,1800.750000,2196.500000
50%,273.500000,2.000000,0.500000,4.000000,0.000000,3.000000,1.000000,1.000000,18.022923,21.811550,58.916650,13.146237,641.000000,3326.500000,4111.500000
75%,455.750000,2.000000,1.000000,5.000000,0.000000,5.000000,1.000000,2.000000,24.651260,28.598750,72.729175,16.789312,1016.250000,4378.500000,5462.000000
max,546.000000,3.000000,1.000000,6.000000,1.000000,6.000000,1.000000,3.000000,34.200847,39.330650,94.826100,34.000021,3410.000000,6456.000000,8362.000000

In [5]:
dfBike_secondHalf.describe()

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,368.000000,368.000000,368.000000,368.000000,368.000000,368.000000,368.000000,368.000000,368.000000,368.000000,368.000000,368.000000,368.000000,368.000000,368.000000
mean,456.000000,3.364130,0.500000,9.494565,0.032609,3.000000,0.679348,1.407609,22.290874,25.859914,65.568135,11.618284,920.040761,4053.741848,4973.782609
std,190.331133,0.769314,0.500681,1.715444,0.177852,2.009514,0.467363,0.569092,7.181837,7.702293,12.418145,4.946368,648.260684,1509.940234,1800.867008
min,182.000000,1.000000,0.000000,7.000000,0.000000,0.000000,0.000000,1.000000,8.849153,11.016650,33.347800,1.500244,2.000000,20.000000,22.000000
25%,273.750000,3.000000,0.000000,8.000000,0.000000,1.000000,0.000000,1.000000,15.605615,19.199150,56.968750,8.333393,429.750000,3114.750000,3784.750000
50%,456.000000,3.000000,0.500000,9.500000,0.000000,3.000000,1.000000,1.000000,22.618327,26.562400,64.854200,11.083609,785.500000,3853.000000,4810.500000
75%,638.250000,4.000000,1.000000,11.000000,0.000000,5.000000,1.000000,2.000000,28.977365,32.701912,73.385425,14.771323,1207.250000,5168.250000,6531.500000
max,730.000000,4.000000,1.000000,12.000000,1.000000,6.000000,1.000000,3.000000,35.328347,42.044800,97.250000,28.292425,3160.000000,6946.000000,8714.000000