In [4]:
import pandas as pd

In [ ]:
Seies is indexed single column
We can have custom index for the same

In [5]:
l=[1,2,3,4,5,6,'Mukudn']
pdSeries=pd.Series(l)
pdSeries

0         1
1         2
2         3
3         4
4         5
5         6
6    Mukudn
dtype: object

In [ ]:
l=[1,2,3,4,5,6,'Mukudn']
pdSeries=pd.Series(l,index=[100,200,300,400,500,600,700]);
pdSeries

In [ ]:
data={"name":['Mukund','AA','BB','CC','DD'],
      "Age":[100,1,32,45,55]};
df=pd.DataFrame(data)
df

In [ ]:
l=[[1,2],[3,5]]
df=pd.DataFrame(l,columns=['First','Second'])
df

In [ ]:
l=[[1,2],[3,5]]
df=pd.DataFrame(l)
df

In [6]:
from pathlib import Path
filePath=Path('../Content')/"BikeIndia.csv"
df=pd.read_csv(filePath)
df

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,1/1/2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,2/1/2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,5/29/2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,5/30/2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,5/31/2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,726,27-12-2019,1,1,12,0,4,1,2,10.420847,11.33210,65.2917,23.458911,247,1867,2114
726,727,28-12-2019,1,1,12,0,5,1,2,10.386653,12.75230,59.0000,10.416557,644,2451,3095
727,728,29-12-2019,1,1,12,0,6,0,2,10.386653,12.12000,75.2917,8.333661,159,1182,1341
728,729,30-12-2019,1,1,12,0,0,0,1,10.489153,11.58500,48.3333,23.500518,364,1432,1796
729,730,31-12-2019,1,1,12,0,1,1,2,8.849153,11.17435,57.7500,10.374682,439,2290,2729

In [ ]:
import pandas as pd
from sqlalchemy import create_engine,text
server="localhost"
database="LogiMojo"

conStr=("mssql+pyodbc:///?odbc_connect="
        f"DRIVER={{ODBC Driver 17 for SQL Server}};"
        f"SERVER={server};DATABASE={database};Trusted_Connection=yes")
engine=create_engine(conStr)

#sql="select  temp,	atemp,	hum	,windspeed,	casual,	registered from [dbo].[BikeIndia]"
sql="select  * from [dbo].[BikeIndia]"

df=pd.read_sql(sql,engine)
#df
df.columns

In [8]:

df.describe()

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000
mean,365.500000,2.498630,0.500000,6.526027,0.028767,2.997260,0.683562,1.394521,20.319259,23.726322,62.765175,12.763620,849.249315,3658.757534,4508.006849
std,210.877136,1.110184,0.500343,3.450215,0.167266,2.006161,0.465405,0.544807,7.506729,8.150308,14.237589,5.195841,686.479875,1559.758728,1936.011647
min,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,2.424346,3.953480,0.000000,1.500244,2.000000,20.000000,22.000000
25%,183.250000,2.000000,0.000000,4.000000,0.000000,1.000000,0.000000,1.000000,13.811885,16.889713,52.000000,9.041650,316.250000,2502.250000,3169.750000
50%,365.500000,3.000000,0.500000,7.000000,0.000000,3.000000,1.000000,1.000000,20.465826,24.368225,62.625000,12.125325,717.000000,3664.500000,4548.500000
75%,547.750000,3.000000,1.000000,10.000000,0.000000,5.000000,1.000000,2.000000,26.880615,30.445775,72.989575,15.625589,1096.500000,4783.250000,5966.000000
max,730.000000,4.000000,1.000000,12.000000,1.000000,6.000000,1.000000,3.000000,35.328347,42.044800,97.250000,34.000021,3410.000000,6946.000000,8714.000000

In [9]:
df.tail()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
725,726,27-12-2019,1,1,12,0,4,1,2,10.420847,11.33210,65.2917,23.458911,247,1867,2114
726,727,28-12-2019,1,1,12,0,5,1,2,10.386653,12.75230,59.0000,10.416557,644,2451,3095
727,728,29-12-2019,1,1,12,0,6,0,2,10.386653,12.12000,75.2917,8.333661,159,1182,1341
728,729,30-12-2019,1,1,12,0,0,0,1,10.489153,11.58500,48.3333,23.500518,364,1432,1796
729,730,31-12-2019,1,1,12,0,1,1,2,8.849153,11.17435,57.7500,10.374682,439,2290,2729

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     730 non-null    int64
 1   dteday      730 non-null    object
 2   season      730 non-null    int64
 3   yr          730 non-null    int64
 4   mnth        730 non-null    int64
 5   holiday     730 non-null    int64
 6   weekday     730 non-null    int64
 7   workingday  730 non-null    int64
 8   weathersit  730 non-null    int64
 9   temp        730 non-null    float64
 10  atemp       730 non-null    float64
 11  hum         730 non-null    float64
 12  windspeed   730 non-null    float64
 13  casual      730 non-null    int64
 14  registered  730 non-null    int64
 15  cnt         730 non-null    int64
dtypes: float64(4), int64(11), object(1)
memory usage: 91.4+ KB

In [11]:
df.shape

(730, 16)

In [12]:
df['mnth']

0       1
1       1
2       1
3       1
4       1
       ..
725    12
726    12
727    12
728    12
729    12
Name: mnth, Length: 730, dtype: int64

In [13]:
type(df['holiday'])

pandas.core.series.Series

In [15]:
df[df['mnth']<=3]

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,1/1/2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,2/1/2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,5/29/2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,5/30/2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,5/31/2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,451,27-03-2019,2,1,3,0,2,1,1,13.256653,15.78270,29.0000,12.541864,531,4571,5102
451,452,28-03-2019,2,1,3,0,3,1,1,19.850847,23.54750,48.1250,19.541957,674,5024,5698
452,453,29-03-2019,2,1,3,0,4,1,1,20.260847,24.11520,43.9167,21.416550,834,5299,6133
453,454,30-03-2019,2,1,3,0,5,1,2,15.170000,18.78105,58.0833,9.250489,796,4663,5459
454,455,31-03-2019,2,1,3,0,6,0,2,17.390847,21.08540,73.8333,16.791339,2301,3934,6235

In [ ]:
type(df[df['mnth']<=3])

In [19]:
df[df['holiday']!=None]

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,1/1/2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,2/1/2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,5/29/2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,5/30/2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,5/31/2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,726,27-12-2019,1,1,12,0,4,1,2,10.420847,11.33210,65.2917,23.458911,247,1867,2114
726,727,28-12-2019,1,1,12,0,5,1,2,10.386653,12.75230,59.0000,10.416557,644,2451,3095
727,728,29-12-2019,1,1,12,0,6,0,2,10.386653,12.12000,75.2917,8.333661,159,1182,1341
728,729,30-12-2019,1,1,12,0,0,0,1,10.489153,11.58500,48.3333,23.500518,364,1432,1796
729,730,31-12-2019,1,1,12,0,1,1,2,8.849153,11.17435,57.7500,10.374682,439,2290,2729

In [21]:
df[df.holiday==1]

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
16,17,17-01-2018,1,0,1,1,1,0,2,7.209153,8.83855,53.7500,12.999139,117,883,1000
51,52,21-02-2018,1,0,2,1,1,0,2,12.436653,14.20375,60.5000,20.625682,195,912,1107
104,105,15-04-2018,2,0,4,1,5,0,1,18.313347,22.09565,67.1250,15.167125,642,2484,3126
149,150,30-05-2018,2,0,5,1,1,0,1,30.066653,33.55460,68.5000,8.792075,1549,2549,4098
184,185,4/7/2018,3,0,7,1,1,0,2,29.793347,33.27085,63.7917,5.459106,3065,2978,6043
247,248,5/9/2018,3,0,9,1,1,0,2,27.606653,31.28230,79.0417,14.250632,1236,2115,3351
282,283,10/10/2018,4,0,10,1,1,0,1,23.404153,27.14625,73.3750,2.834381,1514,3603,5117
314,315,11/11/2018,4,0,11,1,5,0,1,13.290847,15.34085,44.6250,21.083225,440,2928,3368
327,328,24-11-2018,4,0,11,1,4,0,1,15.306653,18.62355,54.9167,11.209368,560,935,1495
359,360,26-12-2018,1,0,12,1,1,0,1,13.191299,15.77675,50.6957,16.044155,430,887,1317
366,367,2/1/2019,1,1,1,1,1,0,1,11.194763,12.61520,38.1304,22.087555,244,1707,1951
380,381,16-01-2019,1,1,1,1,1,0,1,7.790000,9.53315,52.2500,15.500986,217,2081,2298
415,416,20-02-2019,1,1,2,1,1,0,1,11.480000,13.66955,50.7826,15.348561,502,2627,3129
470,471,16-04-2019,2,1,4,1,1,0,1,27.230847,30.74625,56.1667,19.083543,1198,5172,6370
512,513,28-05-2019,2,1,5,1,1,0,1,29.212500,33.96500,67.6250,13.166907,2557,3486,6043
549,550,4/7/2019,3,1,7,1,3,0,1,32.355847,36.61685,53.8750,9.041650,2562,4841,7403
610,611,3/9/2019,3,1,9,1,1,0,1,29.007500,33.08145,79.0833,10.125107,1965,4069,6034
645,646,8/10/2019,4,1,10,1,1,0,2,15.716653,19.38040,70.9583,12.708493,874,4604,5478
680,681,12/11/2019,4,1,11,1,1,0,1,19.885000,23.76915,74.1667,11.625639,1097,5172,6269
690,691,22-11-2019,4,1,11,1,4,0,1,13.940000,17.51855,58.0417,3.542344,955,1470,2425
723,724,25-12-2019,1,1,12,1,2,0,2,11.943464,14.72325,73.4783,11.304642,440,573,1013

In [17]:
df[['holiday','mnth','weekday']]

     holiday  mnth  weekday
0          0     1        6
1          0     1        0
2          0     1        1
3          0     1        2
4          0     1        3
..       ...   ...      ...
725        0    12        4
726        0    12        5
727        0    12        6
728        0    12        0
729        0    12        1

[730 rows x 3 columns]

In [23]:
df[['holiday','mnth','weekday']]

     holiday  mnth  weekday
0          0     1        6
1          0     1        0
2          0     1        1
3          0     1        2
4          0     1        3
..       ...   ...      ...
725        0    12        4
726        0    12        5
727        0    12        6
728        0    12        0
729        0    12        1

[730 rows x 3 columns]

In [25]:
df[['holiday','mnth','weekday']][:10]

   holiday  mnth  weekday
0        0     1        6
1        0     1        0
2        0     1        1
3        0     1        2
4        0     1        3
5        0     1        4
6        0     1        5
7        0     1        6
8        0     1        0
9        0     1        1

In [26]:
df[['holiday','mnth','weekday']][:10:2]

   holiday  mnth  weekday
0        0     1        6
2        0     1        1
4        0     1        3
6        0     1        5
8        0     1        0

In [22]:
df[['holiday','mnth','weekday']][:10:-2]

     holiday  mnth  weekday
729        0    12        1
727        0    12        6
725        0    12        4
723        1    12        2
721        0    12        0
..       ...   ...      ...
19         0     1        4
17         0     1        2
15         0     1        0
13         0     1        5
11         0     1        3

[360 rows x 3 columns]

In [ ]:
#Index based Slicing
#iloc(Row,Column) - both are optional
type(df.iloc[8:10,1:3])

pandas.core.frame.DataFrame

In [29]:
#Index based Slicing
df.iloc[8]

instant              9
dteday        6/4/2018
season               1
yr                   0
mnth                 1
holiday              0
weekday              0
workingday           0
weathersit           1
temp          5.671653
atemp          5.80875
hum            43.4167
windspeed     24.25065
casual              54
registered         768
cnt                822
Name: 8, dtype: object

In [37]:
df.iloc[[1,2,3],:]

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
1,2,2/1/2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,5/29/2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,5/30/2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562

In [38]:
df.iloc[:,[1,2,4]]

         dteday  season  mnth
0      1/1/2018       1     1
1      2/1/2018       1     1
2     5/29/2018       1     1
3     5/30/2018       1     1
4     5/31/2018       1     1
..          ...     ...   ...
725  27-12-2019       1    12
726  28-12-2019       1    12
727  29-12-2019       1    12
728  30-12-2019       1    12
729  31-12-2019       1    12

[730 rows x 3 columns]

In [39]:
df.iloc[8:10,1:3]

     dteday  season
8  6/4/2018       1
9  6/5/2018       1

In [ ]:
#df.iloc[8:10:-1,1:3] #Will not supply any rows
df.iloc[9:7:-1,1:3]

     dteday  season
9  6/5/2018       1
8  6/4/2018       1

In [45]:
df.iloc[9:7:-1,1:3].describe()

       season
count     2.0
mean      1.0
std       0.0
min       1.0
25%       1.0
50%       1.0
75%       1.0
max       1.0

In [76]:
#df.loc[:7:-1]
df.iloc[:7:-1]

,instant,dteday,season,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
yr,,,,,,,,,,,,,,,
1,730,31-12-2019,1,12,0,1,1,2,8.849153,11.17435,57.7500,10.374682,439,2290,2729
1,729,30-12-2019,1,12,0,0,0,1,10.489153,11.58500,48.3333,23.500518,364,1432,1796
1,728,29-12-2019,1,12,0,6,0,2,10.386653,12.12000,75.2917,8.333661,159,1182,1341
1,727,28-12-2019,1,12,0,5,1,2,10.386653,12.75230,59.0000,10.416557,644,2451,3095
1,726,27-12-2019,1,12,0,4,1,2,10.420847,11.33210,65.2917,23.458911,247,1867,2114
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,13,6/8/2018,1,1,0,4,1,1,6.765000,7.54415,47.0417,20.167000,38,1368,1406
0,12,6/7/2018,1,1,0,3,1,1,7.081807,8.02365,59.9545,20.410009,25,1137,1162
0,11,6/6/2018,1,1,0,2,1,2,6.932731,9.57320,68.6364,8.182844,43,1220,1263
0,10,6/5/2018,1,1,0,1,1,1,6.184153,7.54440,48.2917,14.958889,41,1280,1321
0,9,6/4/2018,1,1,0,0,0,1,5.671653,5.80875,43.4167,24.250650,54,768,822

In [75]:
df.loc[:20,'dteday':'yr']

KeyError: 'yr'

In [79]:
df.set_index('dteday',inplace=True)
df.head()

,instant,season,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
dteday,,,,,,,,,,,,,,
1/1/2018,1,1,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
2/1/2018,2,1,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
5/29/2018,3,1,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
5/30/2018,4,1,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
5/31/2018,5,1,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600

In [83]:
df.loc[:,'yr']

KeyError: 'yr'

In [82]:
df.reset_index(inplace=True)

In [90]:
df[df.holiday>0][['dteday','weekday','holiday']]

         dteday  weekday  holiday
16   17-01-2018        1        1
51   21-02-2018        1        1
104  15-04-2018        5        1
149  30-05-2018        1        1
184    4/7/2018        1        1
247    5/9/2018        1        1
282  10/10/2018        1        1
314  11/11/2018        5        1
327  24-11-2018        4        1
359  26-12-2018        1        1
366    2/1/2019        1        1
380  16-01-2019        1        1
415  20-02-2019        1        1
470  16-04-2019        1        1
512  28-05-2019        1        1
549    4/7/2019        3        1
610    3/9/2019        1        1
645   8/10/2019        1        1
680  12/11/2019        1        1
690  22-11-2019        4        1
723  25-12-2019        2        1

In [92]:
df['count_double']=df['cnt'].apply(lambda x: x*2)
df.head()

,dteday,instant,season,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt,count_double
0,1/1/2018,1,1,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985,1970
1,2/1/2018,2,1,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801,1602
2,5/29/2018,3,1,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349,2698
3,5/30/2018,4,1,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562,3124
4,5/31/2018,5,1,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600,3200